/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT0_26 (coord F10), P0_26/J2[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CORE1_LCD_RS_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CORE1_LCD_RS_GPIO_PIN 26U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_CORE1_LCD_RS_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CORE1_LCD_RS_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CORE1_LCD_RS_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CORE1_LCD_RS_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_28 (coord E8), P0_28/J2[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CORE1_LCD_RST_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CORE1_LCD_RST_GPIO_PIN 28U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_CORE1_LCD_RST_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_CORE1_LCD_RST_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_CORE1_LCD_RST_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CORE1_LCD_RST_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Core1(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
