/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE_dse1 0x01u /*!<@brief Drive Strength Enable: High */
#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT1_8 (coord A1), P1_8/J9[32]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[30]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT1_12 (coord D2), P1_12/J2[11]/J9[28]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BLIGHT_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_BLIGHT_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_BLIGHT_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_BLIGHT_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_BLIGHT_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BLIGHT_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT4_1 (coord P2), P4_1/J8[3]/SJ15[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_FRAMEDBG_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_FRAMEDBG_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_FRAMEDBG_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_FRAMEDBG_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_FRAMEDBG_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_FRAMEDBG_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT0_27 (coord E10), P0_27/SJ6[1]
  @{ */

/* Symbols to be used with PORT driver */
#define LPSPI1_INITPINS_LED_GREEN_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define LPSPI1_INITPINS_LED_GREEN_PIN 27U                   /*!<@brief PORT pin number */
#define LPSPI1_INITPINS_LED_GREEN_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT0_26 (coord F10), P0_26/J2[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define LPSPI1_INITPINS_LCD_RS_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define LPSPI1_INITPINS_LCD_RS_GPIO_PIN 26U              /*!<@brief GPIO pin number */
#define LPSPI1_INITPINS_LCD_RS_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LPSPI1_INITPINS_LCD_RS_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define LPSPI1_INITPINS_LCD_RS_PIN 26U                   /*!<@brief PORT pin number */
#define LPSPI1_INITPINS_LCD_RS_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT0_28 (coord E8), P0_28/J2[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define LPSPI1_INITPINS_LCD_RES_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define LPSPI1_INITPINS_LCD_RES_GPIO_PIN 28U              /*!<@brief GPIO pin number */
#define LPSPI1_INITPINS_LCD_RES_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LPSPI1_INITPINS_LCD_RES_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define LPSPI1_INITPINS_LCD_RES_PIN 28U                   /*!<@brief PORT pin number */
#define LPSPI1_INITPINS_LCD_RES_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI1_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
