
#ifndef AVC_CAMERA__MASTER_CONFIG_H_
#define AVC_CAMERA__MASTER_CONFIG_H_


#define CAMERA__OV7670							1
#define CAMERA__OV5460  						2

//supported OV5640:
//FSL_VIDEO_RESOLUTION(320,200):
//FSL_VIDEO_RESOLUTION(320,102):
//FSL_VIDEO_RESOLUTION(160,120):
//FSL_VIDEO_RESOLUTION(320,240):

#define CONFIG__CAMERA_SELECT					(CAMERA__OV5640)

#define CONFIG__CAMERA_RESOLUTION				FSL_VIDEO_RESOLUTION(320, 200)

#define CONFIG__CAMERA_RESOLUTION_X				FSL_VIDEO_EXTRACT_WIDTH(CONFIG__CAMERA_RESOLUTION)

#define CONFIG__CAMERA_RESOLUTION_Y				FSL_VIDEO_EXTRACT_HEIGHT(CONFIG__CAMERA_RESOLUTION)

//#define CONFIG__OV7670_IS_160x120 (1)           // This only applies to the OV7670

#if CONFIG__CAMERA_SELECT == CAMERA__OV7670

#if CONFIG__OV7670_IS_160x120 == 1
#define DEMO_BUFFER_WIDTH 120
#define DEMO_BUFFER_HEIGHT 160
#define DEMO_CAMERA_RESOLUTION kVIDEO_ResolutionQQVGA /* 160x120 */
#define DEMO_SMARTDMA_API kSMARTDMA_CameraWholeFrameQVGA
#else
#define DEMO_BUFFER_WIDTH 240
#define DEMO_BUFFER_HEIGHT 320
#define DEMO_CAMERA_RESOLUTION kVIDEO_ResolutionQVGA /* 320*240 */
#define DEMO_SMARTDMA_API kSMARTDMA_CameraWholeFrameQVGA
#endif

#elif CONFIG__CAMERA_SELECT == CAMERA__OV5640

#else

#error Invalid camera selection.

#endif

#endif
